"
" This file was automatically generated by riml 0.2.10
" Modify with care!
"
function! s:SID()
  return matchstr(expand('<sfile>'), '<SNR>\zs\d\+\ze_SID$')
endfunction
" included: 'logger.riml'
function! g:LoggerConstructor()
  let loggerObj = {}
  let loggerObj.messages = []
  let loggerObj.log_writers = []
  let loggerObj.level = 'info'
  let loggerObj.levels = {}
  let loggerObj.levels.all = 0
  let loggerObj.levels.debug = 1
  let loggerObj.levels.info = 2
  let loggerObj.levels.warn = 3
  let loggerObj.levels.error = 4
  let loggerObj.levels.fatal = 5
  let loggerObj.levels.off = 6
  let loggerObj.colors = {}
  let loggerObj.colors.all = 0
  let loggerObj.colors.debug = 0
  let loggerObj.colors.info = 0
  let loggerObj.colors.warn = '31m'
  let loggerObj.colors.error = '31m'
  let loggerObj.colors.fatal = '31m'
  let loggerObj.colors.off = 0
  let loggerObj.add_log_writer = function('<SNR>' . s:SID() . '_s:Logger_add_log_writer')
  let loggerObj.set_level = function('<SNR>' . s:SID() . '_s:Logger_set_level')
  let loggerObj.get_level = function('<SNR>' . s:SID() . '_s:Logger_get_level')
  let loggerObj.get_level_num = function('<SNR>' . s:SID() . '_s:Logger_get_level_num')
  let loggerObj.is_loggable = function('<SNR>' . s:SID() . '_s:Logger_is_loggable')
  let loggerObj.do_log = function('<SNR>' . s:SID() . '_s:Logger_do_log')
  let loggerObj.args_to_message = function('<SNR>' . s:SID() . '_s:Logger_args_to_message')
  let loggerObj.send_log = function('<SNR>' . s:SID() . '_s:Logger_send_log')
  let loggerObj.to_color = function('<SNR>' . s:SID() . '_s:Logger_to_color')
  let loggerObj.debug = function('<SNR>' . s:SID() . '_s:Logger_debug')
  let loggerObj.info = function('<SNR>' . s:SID() . '_s:Logger_info')
  let loggerObj.log = function('<SNR>' . s:SID() . '_s:Logger_log')
  let loggerObj.warn = function('<SNR>' . s:SID() . '_s:Logger_warn')
  let loggerObj.error = function('<SNR>' . s:SID() . '_s:Logger_error')
  let loggerObj.fatal = function('<SNR>' . s:SID() . '_s:Logger_fatal')
  return loggerObj
endfunction
function! <SID>s:Logger_add_log_writer(log_writer) dict
  call add(self.log_writers, a:log_writer)
endfunction
function! <SID>s:Logger_set_level(level) dict
  let self.level = a:level
endfunction
function! <SID>s:Logger_get_level() dict
  return self.level
endfunction
function! <SID>s:Logger_get_level_num(level) dict
  return self.levels[a:level]
endfunction
function! <SID>s:Logger_is_loggable(level) dict
  return self.get_level_num(a:level) >=# self.get_level_num(self.level)
endfunction
function! <SID>s:Logger_do_log(args, level) dict
  if self.is_loggable(a:level)
    let msg = self.args_to_message(a:args)
    call self.send_log(msg, a:level)
  endif
endfunction
function! <SID>s:Logger_args_to_message(args) dict
  return join(a:args, ' ')
endfunction
function! <SID>s:Logger_send_log(msg, level) dict
  let color_msg = self.to_color(a:msg, a:level)
  for log_writer in self.log_writers
    if log_writer.get_colorize()
      call log_writer.log(color_msg)
    else
      call log_writer.log(a:msg)
    endif
  endfor
endfunction
function! <SID>s:Logger_to_color(msg, level) dict
  let color = self.colors[a:level]
  if color !=# 0
    return "[" . color . a:msg . "[0m"
  else
    return a:msg
  endif
endfunction
function! <SID>s:Logger_debug(...) dict
  call self.do_log(a:000, 'debug')
endfunction
function! <SID>s:Logger_info(...) dict
  call self.do_log(a:000, 'info')
endfunction
function! <SID>s:Logger_log(...) dict
  call self.do_log(a:000, 'info')
endfunction
function! <SID>s:Logger_warn(...) dict
  call self.do_log(a:000, 'warn')
endfunction
function! <SID>s:Logger_error(...) dict
  call self.do_log(a:000, 'error')
endfunction
function! <SID>s:Logger_fatal(...) dict
  call self.do_log(a:000, 'fatal')
endfunction
function! s:get_logger()
  if !(exists('g:logger'))
    let g:logger = g:LoggerConstructor()
  endif
  return g:logger
endfunction
let s:logger = s:get_logger()
" included: 'echo_log_writer.riml'
function! s:EchoLogWriterConstructor()
  let echoLogWriterObj = {}
  let echoLogWriterObj.get_colorize = function('<SNR>' . s:SID() . '_s:EchoLogWriter_get_colorize')
  let echoLogWriterObj.log = function('<SNR>' . s:SID() . '_s:EchoLogWriter_log')
  return echoLogWriterObj
endfunction
function! <SID>s:EchoLogWriter_get_colorize() dict
  return 0
endfunction
function! <SID>s:EchoLogWriter_log(message) dict
  echo a:message
endfunction
" included: 'spec_timer.riml'
function! s:SpecTimerConstructor()
  let specTimerObj = {}
  let specTimerObj.start_time = 0
  let specTimerObj.end_time = 0
  let specTimerObj.start = function('<SNR>' . s:SID() . '_s:SpecTimer_start')
  let specTimerObj.stop = function('<SNR>' . s:SID() . '_s:SpecTimer_stop')
  let specTimerObj.get_duration = function('<SNR>' . s:SID() . '_s:SpecTimer_get_duration')
  let specTimerObj.time_to_ms = function('<SNR>' . s:SID() . '_s:SpecTimer_time_to_ms')
  return specTimerObj
endfunction
function! <SID>s:SpecTimer_start() dict
  let self.start_time = reltime()
endfunction
function! <SID>s:SpecTimer_stop() dict
  let self.end_time = reltime()
  let self.duration = self.time_to_ms(reltime(self.start_time))
endfunction
function! <SID>s:SpecTimer_get_duration() dict
  return self.duration
endfunction
function! <SID>s:SpecTimer_time_to_ms(time) dict
  let duration_str = reltimestr(a:time)
  let duration_split = split(duration_str, '\.')
  let seconds = str2nr(duration_split[0])
  let microseconds = str2nr(duration_split[1])
  let milliseconds = (seconds * 1000) + (microseconds / 1000)
  return milliseconds
endfunction
" included: 'spec_meta.riml'
function! s:SpecMetaConstructor(context, method)
  let specMetaObj = {}
  let specMetaObj.context = a:context
  let specMetaObj.method = a:method
  let specMetaObj.get_context = function('<SNR>' . s:SID() . '_s:SpecMeta_get_context')
  let specMetaObj.get_method = function('<SNR>' . s:SID() . '_s:SpecMeta_get_method')
  let specMetaObj.get_sentence = function('<SNR>' . s:SID() . '_s:SpecMeta_get_sentence')
  let specMetaObj.set_duration = function('<SNR>' . s:SID() . '_s:SpecMeta_set_duration')
  let specMetaObj.get_duration = function('<SNR>' . s:SID() . '_s:SpecMeta_get_duration')
  let specMetaObj.is_slow = function('<SNR>' . s:SID() . '_s:SpecMeta_is_slow')
  return specMetaObj
endfunction
function! <SID>s:SpecMeta_get_context() dict
  return self.context
endfunction
function! <SID>s:SpecMeta_get_method() dict
  return self.method
endfunction
function! <SID>s:SpecMeta_get_sentence() dict
  return substitute(self.get_method(), '_', ' ', 'g')
endfunction
function! <SID>s:SpecMeta_set_duration(duration) dict
  let self.duration = a:duration
endfunction
function! <SID>s:SpecMeta_get_duration() dict
  return self.duration
endfunction
function! <SID>s:SpecMeta_is_slow() dict
  return self.get_duration() ># g:speckle_slow_threshold
endfunction
" included: 'statistician.riml'
function! s:StatisticianConstructor()
  let statisticianObj = {}
  let statisticianObj.count = 0
  let statisticianObj.passes = 0
  let statisticianObj.failures = 0
  let statisticianObj.errors = 0
  let statisticianObj.pending = 0
  let statisticianObj.inc_count = function('<SNR>' . s:SID() . '_s:Statistician_inc_count')
  let statisticianObj.inc_passes = function('<SNR>' . s:SID() . '_s:Statistician_inc_passes')
  let statisticianObj.inc_failures = function('<SNR>' . s:SID() . '_s:Statistician_inc_failures')
  let statisticianObj.inc_pending = function('<SNR>' . s:SID() . '_s:Statistician_inc_pending')
  let statisticianObj.inc_errors = function('<SNR>' . s:SID() . '_s:Statistician_inc_errors')
  let statisticianObj.inc_assertions = function('<SNR>' . s:SID() . '_s:Statistician_inc_assertions')
  let statisticianObj.get_count = function('<SNR>' . s:SID() . '_s:Statistician_get_count')
  let statisticianObj.get_passes = function('<SNR>' . s:SID() . '_s:Statistician_get_passes')
  let statisticianObj.get_failures = function('<SNR>' . s:SID() . '_s:Statistician_get_failures')
  let statisticianObj.get_pending = function('<SNR>' . s:SID() . '_s:Statistician_get_pending')
  let statisticianObj.get_errors = function('<SNR>' . s:SID() . '_s:Statistician_get_errors')
  let statisticianObj.get_assertions = function('<SNR>' . s:SID() . '_s:Statistician_get_assertions')
  let statisticianObj.is_ok = function('<SNR>' . s:SID() . '_s:Statistician_is_ok')
  let statisticianObj.is_not_ok = function('<SNR>' . s:SID() . '_s:Statistician_is_not_ok')
  return statisticianObj
endfunction
function! <SID>s:Statistician_inc_count() dict
  let self.count += 1
endfunction
function! <SID>s:Statistician_inc_passes() dict
  call self.inc_count()
  let self.passes += 1
endfunction
function! <SID>s:Statistician_inc_failures() dict
  call self.inc_count()
  let self.failures += 1
endfunction
function! <SID>s:Statistician_inc_pending() dict
  call self.inc_count()
  let self.pending += 1
endfunction
function! <SID>s:Statistician_inc_errors() dict
  call self.inc_count()
  let self.errors += 1
endfunction
function! <SID>s:Statistician_inc_assertions() dict
  let env = g:speckle_env
  let env.assertions += 1
endfunction
function! <SID>s:Statistician_get_count() dict
  return self.count
endfunction
function! <SID>s:Statistician_get_passes() dict
  return self.passes
endfunction
function! <SID>s:Statistician_get_failures() dict
  return self.failures
endfunction
function! <SID>s:Statistician_get_pending() dict
  return self.pending
endfunction
function! <SID>s:Statistician_get_errors() dict
  return self.errors
endfunction
function! <SID>s:Statistician_get_assertions() dict
  return g:speckle_env.assertions
endfunction
function! <SID>s:Statistician_is_ok() dict
  return self.get_errors() ==# 0 && self.get_failures() ==# 0
endfunction
function! <SID>s:Statistician_is_not_ok() dict
  return !self.is_ok()
endfunction
" included: 'equality_matcher.riml'
function! s:EqualityMatcherConstructor()
  let equalityMatcherObj = {}
  let equalityMatcherObj.match = function('<SNR>' . s:SID() . '_s:EqualityMatcher_match')
  let equalityMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:EqualityMatcher_failure_message_for_match')
  let equalityMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:EqualityMatcher_failure_message_for_mismatch')
  return equalityMatcherObj
endfunction
function! <SID>s:EqualityMatcher_match(expected, actual) dict
  return a:actual ==# a:expected
endfunction
function! <SID>s:EqualityMatcher_failure_message_for_match(expected, actual) dict
  return "expected “" . a:actual . "” to equal “" . a:expected . "”"
endfunction
function! <SID>s:EqualityMatcher_failure_message_for_mismatch(expected, actual) dict
  return "expected “" . a:actual . "” to not equal “" . a:expected . "”"
endfunction
" included: 'boolean_matcher.riml'
function! s:BooleanMatcherConstructor()
  let booleanMatcherObj = {}
  let booleanMatcherObj.match = function('<SNR>' . s:SID() . '_s:BooleanMatcher_match')
  let booleanMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:BooleanMatcher_failure_message_for_match')
  let booleanMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:BooleanMatcher_failure_message_for_mismatch')
  return booleanMatcherObj
endfunction
function! <SID>s:BooleanMatcher_match(expected, actual) dict
  return a:actual ==# 1
endfunction
function! <SID>s:BooleanMatcher_failure_message_for_match(expected, actual) dict
  return "expected “" . a:actual . "” to be true"
endfunction
function! <SID>s:BooleanMatcher_failure_message_for_mismatch(expected, actual) dict
  return "expected “" . a:actual . "” to be false"
endfunction
" included: 'existance_matcher.riml'
function! s:ExistanceMatcherConstructor()
  let existanceMatcherObj = {}
  let existanceMatcherObj.match = function('<SNR>' . s:SID() . '_s:ExistanceMatcher_match')
  let existanceMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:ExistanceMatcher_failure_message_for_match')
  let existanceMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:ExistanceMatcher_failure_message_for_mismatch')
  return existanceMatcherObj
endfunction
function! <SID>s:ExistanceMatcher_match(expected, actual) dict
  return exists(a:actual)
endfunction
function! <SID>s:ExistanceMatcher_failure_message_for_match(expected, actual) dict
  return "expected “" . a:actual . "” to exist"
endfunction
function! <SID>s:ExistanceMatcher_failure_message_for_mismatch(expected, actual) dict
  return "expected “" . a:actual . "” to not exist"
endfunction
" included: 'above_matcher.riml'
function! s:AboveMatcherConstructor()
  let aboveMatcherObj = {}
  let aboveMatcherObj.match = function('<SNR>' . s:SID() . '_s:AboveMatcher_match')
  let aboveMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:AboveMatcher_failure_message_for_match')
  let aboveMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:AboveMatcher_failure_message_for_mismatch')
  return aboveMatcherObj
endfunction
function! <SID>s:AboveMatcher_match(expected, actual) dict
  return a:actual ># a:expected
endfunction
function! <SID>s:AboveMatcher_failure_message_for_match(expected, actual) dict
  return "expected “" . a:actual . "” to be above “" . a:expected . "”"
endfunction
function! <SID>s:AboveMatcher_failure_message_for_mismatch(expected, actual) dict
  return "expected “" . a:actual . "” to not be above “" . a:expected . "”"
endfunction
" included: 'below_matcher.riml'
function! s:BelowMatcherConstructor()
  let belowMatcherObj = {}
  let belowMatcherObj.match = function('<SNR>' . s:SID() . '_s:BelowMatcher_match')
  let belowMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:BelowMatcher_failure_message_for_match')
  let belowMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:BelowMatcher_failure_message_for_mismatch')
  return belowMatcherObj
endfunction
function! <SID>s:BelowMatcher_match(expected, actual) dict
  return a:actual <# a:expected
endfunction
function! <SID>s:BelowMatcher_failure_message_for_match(expected, actual) dict
  return "expected “" . a:actual . "” to be below “" . a:expected . "”"
endfunction
function! <SID>s:BelowMatcher_failure_message_for_mismatch(expected, actual) dict
  return "expected “" . a:actual . "” to not be below “" . a:expected . "”"
endfunction
" included: 'between_matcher.riml'
function! s:BetweenMatcherConstructor()
  let betweenMatcherObj = {}
  let betweenMatcherObj.match = function('<SNR>' . s:SID() . '_s:BetweenMatcher_match')
  let betweenMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:BetweenMatcher_failure_message_for_match')
  let betweenMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:BetweenMatcher_failure_message_for_mismatch')
  return betweenMatcherObj
endfunction
function! <SID>s:BetweenMatcher_match(bounds, actual) dict
  let min = a:bounds[0]
  let max = a:bounds[1]
  return a:actual >=# min && a:actual <=# max
endfunction
function! <SID>s:BetweenMatcher_failure_message_for_match(bounds, actual) dict
  let min = a:bounds[0]
  let max = a:bounds[1]
  return "expected “" . a:actual . "” to be between “" . min . " .. " . max . "”"
endfunction
function! <SID>s:BetweenMatcher_failure_message_for_mismatch(bounds, actual) dict
  let min = a:bounds[0]
  let max = a:bounds[1]
  return "expected “" . a:actual . "” to not be between “" . min . " .. " . max . "”"
endfunction
" included: 'length_matcher.riml'
function! s:LengthMatcherConstructor()
  let lengthMatcherObj = {}
  let lengthMatcherObj.match = function('<SNR>' . s:SID() . '_s:LengthMatcher_match')
  let lengthMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:LengthMatcher_failure_message_for_match')
  let lengthMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:LengthMatcher_failure_message_for_mismatch')
  return lengthMatcherObj
endfunction
function! <SID>s:LengthMatcher_match(expected, actual) dict
  let self.result = len(a:actual)
  return self.result ==# a:expected
endfunction
function! <SID>s:LengthMatcher_failure_message_for_match(expected, actual) dict
  return "expected length of “" . a:actual . "” to be “" . a:expected . "”, but was " . self.result
endfunction
function! <SID>s:LengthMatcher_failure_message_for_mismatch(expected, actual) dict
  return "expected length of “" . a:actual . "” to not be “" . a:expected . "”, but was " . self.result
endfunction
" included: 'atleast_matcher.riml'
function! s:AtleastMatcherConstructor()
  let atleastMatcherObj = {}
  let atleastMatcherObj.match = function('<SNR>' . s:SID() . '_s:AtleastMatcher_match')
  let atleastMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:AtleastMatcher_failure_message_for_match')
  let atleastMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:AtleastMatcher_failure_message_for_mismatch')
  return atleastMatcherObj
endfunction
function! <SID>s:AtleastMatcher_match(expected, actual) dict
  return a:actual >=# a:expected
endfunction
function! <SID>s:AtleastMatcher_failure_message_for_match(expected, actual) dict
  return "expected “" . a:actual . "” to be greater than or equal to “" . a:expected . "”"
endfunction
function! <SID>s:AtleastMatcher_failure_message_for_mismatch(expected, actual) dict
  return "expected “" . a:actual . "” to not be greater than or equal to “" . a:expected . "”"
endfunction
" included: 'atmost_matcher.riml'
function! s:AtmostMatcherConstructor()
  let atmostMatcherObj = {}
  let atmostMatcherObj.match = function('<SNR>' . s:SID() . '_s:AtmostMatcher_match')
  let atmostMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:AtmostMatcher_failure_message_for_match')
  let atmostMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:AtmostMatcher_failure_message_for_mismatch')
  return atmostMatcherObj
endfunction
function! <SID>s:AtmostMatcher_match(expected, actual) dict
  return a:actual <=# a:expected
endfunction
function! <SID>s:AtmostMatcher_failure_message_for_match(expected, actual) dict
  return "expected “" . a:actual . "” to be less than or equal to “" . a:expected . "”"
endfunction
function! <SID>s:AtmostMatcher_failure_message_for_mismatch(expected, actual) dict
  return "expected “" . a:actual . "” to not be less than or equal to “" . a:expected . "”"
endfunction
" included: 'within_matcher.riml'
function! s:WithinMatcherConstructor()
  let withinMatcherObj = {}
  let withinMatcherObj.match = function('<SNR>' . s:SID() . '_s:WithinMatcher_match')
  let withinMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:WithinMatcher_failure_message_for_match')
  let withinMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:WithinMatcher_failure_message_for_mismatch')
  return withinMatcherObj
endfunction
function! <SID>s:WithinMatcher_match(expected, actual) dict
  let delta = a:expected[0]
  let num = a:expected[1]
  let self.result = abs(num - a:actual)
  return self.result <=# delta
endfunction
function! <SID>s:WithinMatcher_failure_message_for_match(expected, actual) dict
  let delta = a:expected[0]
  let num = a:expected[1]
  let actual_str = printf("%f", a:actual)
  let delta_str = printf("%f", delta)
  let num_str = printf("%f", num)
  let result_str = printf('%f', self.result)
  return "expected “" . actual_str . "” to be within +/- “" . delta_str . "” of “" . num_str . "”, delta was “" . result_str . "”"
endfunction
function! <SID>s:WithinMatcher_failure_message_for_mismatch(expected, actual) dict
  let delta = a:expected[0]
  let num = a:expected[1]
  let actual_str = printf("%f", a:actual)
  let delta_str = printf("%f", delta)
  let num_str = printf("%f", num)
  let result_str = printf('%f', self.result)
  return "expected “" . actual_str . "” to not be within +/- “" . delta_str . "” of “" . num_str . "”, delta was “" . result_str . "”"
endfunction
" included: 'regexp_matcher.riml'
function! s:RegExpMatcherConstructor()
  let regExpMatcherObj = {}
  let regExpMatcherObj.match = function('<SNR>' . s:SID() . '_s:RegExpMatcher_match')
  let regExpMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:RegExpMatcher_failure_message_for_match')
  let regExpMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:RegExpMatcher_failure_message_for_mismatch')
  return regExpMatcherObj
endfunction
function! <SID>s:RegExpMatcher_match(pattern, expr) dict
  let result = matchstr(a:expr, a:pattern)
  return empty(result) ==# 0
endfunction
function! <SID>s:RegExpMatcher_failure_message_for_match(pattern, expr) dict
  return "expected “" . a:pattern . "” to match " . a:expr
endfunction
function! <SID>s:RegExpMatcher_failure_message_for_mismatch(pattern, expr) dict
  return "expected “" . a:pattern . "” to not match " . a:expr
endfunction
" included: 'dict_key_matcher.riml'
function! s:DictKeyMatcherConstructor()
  let dictKeyMatcherObj = {}
  let dictKeyMatcherObj.match = function('<SNR>' . s:SID() . '_s:DictKeyMatcher_match')
  let dictKeyMatcherObj.failure_message_for_match = function('<SNR>' . s:SID() . '_s:DictKeyMatcher_failure_message_for_match')
  let dictKeyMatcherObj.failure_message_for_mismatch = function('<SNR>' . s:SID() . '_s:DictKeyMatcher_failure_message_for_mismatch')
  return dictKeyMatcherObj
endfunction
function! <SID>s:DictKeyMatcher_match(expected, actual) dict
  return has_key(a:actual, a:expected)
endfunction
function! <SID>s:DictKeyMatcher_failure_message_for_match(expected, actual) dict
  return "expected object to have key “" . a:expected . "”"
endfunction
function! <SID>s:DictKeyMatcher_failure_message_for_mismatch(expected, actual) dict
  return "expected object to not have key “" . a:expected . "”"
endfunction
" included: 'match_item.riml'
function! s:MatchItemConstructor(name, matcher, negate)
  let matchItemObj = {}
  let matchItemObj.name = a:name
  let matchItemObj.matcher = a:matcher
  let matchItemObj.negate = a:negate
  return matchItemObj
endfunction
" included: 'match_tester.riml'
function! g:MatchTesterConstructor()
  let matchTesterObj = {}
  let matchTesterObj.test_from_env = function('<SNR>' . s:SID() . '_s:MatchTester_test_from_env')
  let matchTesterObj.test = function('<SNR>' . s:SID() . '_s:MatchTester_test')
  return matchTesterObj
endfunction
function! <SID>s:MatchTester_test_from_env(matcher_name, expected) dict
  let env = g:speckle_env
  let matchers = env.matchers
  let match_item = matchers.get_match_item(a:matcher_name)
  let negate = match_item.negate
  let matcher = match_item.matcher
  let actual = env.actual
  let tester = g:MatchTesterConstructor()
  call tester.test(matcher, negate, a:expected, actual)
endfunction
function! <SID>s:MatchTester_test(matcher, negate, expected, actual) dict
  let result = a:matcher.match(a:expected, a:actual)
  let g:speckle_env.assertions += 1
  if a:negate
    if result
      let message = a:matcher.failure_message_for_mismatch(a:expected, a:actual)
      let message = "AssertionError: " . message
      throw message
    endif
  else
    if !(result)
      let message = a:matcher.failure_message_for_match(a:expected, a:actual)
      let message = "AssertionError: " . message
      throw message
    endif
  endif
endfunction
" included: 'matchers.riml'
function! g:MatchersConstructor()
  let matchersObj = {}
  let matchersObj.matchers = {}
  let matchersObj.load_defaults = function('<SNR>' . s:SID() . '_s:Matchers_load_defaults')
  let matchersObj.get_match_items = function('<SNR>' . s:SID() . '_s:Matchers_get_match_items')
  let matchersObj.get_match_item = function('<SNR>' . s:SID() . '_s:Matchers_get_match_item')
  let matchersObj.define_single = function('<SNR>' . s:SID() . '_s:Matchers_define_single')
  let matchersObj.define_pair = function('<SNR>' . s:SID() . '_s:Matchers_define_pair')
  return matchersObj
endfunction
function! <SID>s:Matchers_load_defaults() dict
  let matcher = s:EqualityMatcherConstructor()
  call self.define_pair('to_equal', 'to_not_equal', matcher)
  call self.define_pair('to_eq', 'to_neq', matcher)
  let matcher = s:BooleanMatcherConstructor()
  call self.define_pair('to_be_true', 'to_be_false', matcher)
  call self.define_pair('to_be_ok', 'to_not_be_ok', matcher)
  let matcher = s:ExistanceMatcherConstructor()
  call self.define_pair('to_exist', 'to_not_exist', matcher)
  let matcher = s:AboveMatcherConstructor()
  call self.define_pair('to_be_above', 'to_not_be_above', matcher)
  call self.define_pair('to_be_gt', 'to_not_be_gt', matcher)
  let matcher = s:BelowMatcherConstructor()
  call self.define_pair('to_be_below', 'to_not_be_below', matcher)
  call self.define_pair('to_be_lt', 'to_not_be_lt', matcher)
  let matcher = s:BetweenMatcherConstructor()
  call self.define_pair('to_be_between', 'to_not_be_between', matcher)
  let matcher = s:LengthMatcherConstructor()
  call self.define_pair('to_have_length', 'to_not_have_length', matcher)
  let matcher = s:AtleastMatcherConstructor()
  call self.define_pair('to_be_at_least', 'to_not_be_at_least', matcher)
  call self.define_pair('to_be_gte', 'to_not_be_gte', matcher)
  let matcher = s:AtmostMatcherConstructor()
  call self.define_pair('to_be_at_most', 'to_not_be_at_most', matcher)
  call self.define_pair('to_be_lte', 'to_not_be_lte', matcher)
  let matcher = s:WithinMatcherConstructor()
  call self.define_pair('to_be_within', 'to_not_be_within', matcher)
  let matcher = s:RegExpMatcherConstructor()
  call self.define_pair('to_match', 'to_not_match', matcher)
  call self.define_pair('to_have_string', 'to_not_have_string', matcher)
  let matcher = s:DictKeyMatcherConstructor()
  call self.define_pair('to_have_key', 'to_not_have_key', matcher)
endfunction
function! <SID>s:Matchers_get_match_items() dict
  return values(self.matchers)
endfunction
function! <SID>s:Matchers_get_match_item(name) dict
  return self.matchers[a:name]
endfunction
function! <SID>s:Matchers_define_single(name, matcher) dict
  let item = s:MatchItemConstructor(a:name, a:matcher)
  let self.matchers[a:name] = item
endfunction
function! <SID>s:Matchers_define_pair(ok_name, not_ok_name, matcher) dict
  let ok_item = s:MatchItemConstructor(a:ok_name, a:matcher, 0)
  let not_ok_item = s:MatchItemConstructor(a:not_ok_name, a:matcher, 1)
  let self.matchers[a:ok_name] = ok_item
  let self.matchers[a:not_ok_name] = not_ok_item
endfunction
" included: 'file_writer.riml'
function! s:FileWriterConstructor()
  let fileWriterObj = {}
  let fileWriterObj.lines = []
  let fileWriterObj.current_line = ''
  let fileWriterObj.set_output_file = function('<SNR>' . s:SID() . '_s:FileWriter_set_output_file')
  let fileWriterObj.write = function('<SNR>' . s:SID() . '_s:FileWriter_write')
  let fileWriterObj.writeln = function('<SNR>' . s:SID() . '_s:FileWriter_writeln')
  let fileWriterObj.flush_line = function('<SNR>' . s:SID() . '_s:FileWriter_flush_line')
  let fileWriterObj.flush = function('<SNR>' . s:SID() . '_s:FileWriter_flush')
  return fileWriterObj
endfunction
function! <SID>s:FileWriter_set_output_file(output_file) dict
  let self.output_file = a:output_file
endfunction
function! <SID>s:FileWriter_write(line) dict
  let self.current_line = self.current_line . a:line
endfunction
function! <SID>s:FileWriter_writeln(line) dict
  call add(self.lines, self.current_line . a:line)
  let self.current_line = ''
endfunction
function! <SID>s:FileWriter_flush_line() dict
  if !(self.current_line ==# '')
    call add(self.lines, self.current_line)
    let self.current_line = ''
  endif
endfunction
function! <SID>s:FileWriter_flush() dict
  call self.flush_line()
  call writefile(self.lines, self.output_file)
endfunction
" included: 'console_writer.riml'
function! s:ConsoleWriterConstructor()
  let consoleWriterObj = {}
  let consoleWriterObj.writer = s:FileWriterConstructor()
  let consoleWriterObj.set_output_file = function('<SNR>' . s:SID() . '_s:ConsoleWriter_set_output_file')
  let consoleWriterObj.write = function('<SNR>' . s:SID() . '_s:ConsoleWriter_write')
  let consoleWriterObj.writeln = function('<SNR>' . s:SID() . '_s:ConsoleWriter_writeln')
  let consoleWriterObj.flush = function('<SNR>' . s:SID() . '_s:ConsoleWriter_flush')
  let consoleWriterObj.flush_line = function('<SNR>' . s:SID() . '_s:ConsoleWriter_flush_line')
  return consoleWriterObj
endfunction
function! <SID>s:ConsoleWriter_set_output_file(output_file) dict
  call self.writer.set_output_file(a:output_file)
endfunction
function! <SID>s:ConsoleWriter_write(line) dict
  call self.writer.write(a:line)
  echon a:line
endfunction
function! <SID>s:ConsoleWriter_writeln(line) dict
  call self.writer.writeln(a:line)
  echomsg a:line
endfunction
function! <SID>s:ConsoleWriter_flush() dict
  call self.writer.flush()
endfunction
function! <SID>s:ConsoleWriter_flush_line() dict
  call self.writer.flush_line()
endfunction
" included: 'buffer_writer.riml'
function! s:BufferWriterConstructor()
  let bufferWriterObj = {}
  let bufferWriterObj.writer = s:FileWriterConstructor()
  let bufferWriterObj.set_output_file = function('<SNR>' . s:SID() . '_s:BufferWriter_set_output_file')
  let bufferWriterObj.strip_colors = function('<SNR>' . s:SID() . '_s:BufferWriter_strip_colors')
  let bufferWriterObj.write = function('<SNR>' . s:SID() . '_s:BufferWriter_write')
  let bufferWriterObj.writeln = function('<SNR>' . s:SID() . '_s:BufferWriter_writeln')
  let bufferWriterObj.flush = function('<SNR>' . s:SID() . '_s:BufferWriter_flush')
  let bufferWriterObj.flush_line = function('<SNR>' . s:SID() . '_s:BufferWriter_flush_line')
  return bufferWriterObj
endfunction
function! <SID>s:BufferWriter_set_output_file(output_file) dict
  call self.writer.set_output_file(a:output_file)
endfunction
function! <SID>s:BufferWriter_strip_colors(line) dict
  return substitute(a:line, '\e\[[0-9;]\+[mK]', '', 'g')
endfunction
function! <SID>s:BufferWriter_write(line) dict
  call self.writer.write(a:line)
  let line = self.strip_colors(a:line)
  call append(line('$'), line)
  normal gJ
endfunction
function! <SID>s:BufferWriter_writeln(line) dict
  call self.writer.writeln(a:line)
  let line = self.strip_colors(a:line)
  call append(line('$'), line)
  normal G
endfunction
function! <SID>s:BufferWriter_flush() dict
  call self.writer.flush()
endfunction
function! <SID>s:BufferWriter_flush_line() dict
  call self.writer.flush_line()
endfunction
" included: 'writer_factory.riml'
function! s:WriterFactoryConstructor()
  let writerFactoryObj = {}
  let writerFactoryObj.get_writer = function('<SNR>' . s:SID() . '_s:WriterFactory_get_writer')
  return writerFactoryObj
endfunction
function! <SID>s:WriterFactory_get_writer(writer_name) dict
  if a:writer_name ==# 'file'
    return s:FileWriterConstructor()
  elseif a:writer_name ==# 'console'
    return s:ConsoleWriterConstructor()
  elseif a:writer_name ==# 'buffer'
    return s:BufferWriterConstructor()
  else
    return s:BufferWriterConstructor()
  endif
endfunction
" included: 'file_log_writer.riml'
function! s:FileLogWriterConstructor()
  let fileLogWriterObj = {}
  let fileLogWriterObj.writer = s:FileWriterConstructor()
  let fileLogWriterObj.colorize = 1
  let fileLogWriterObj.set_log_file = function('<SNR>' . s:SID() . '_s:FileLogWriter_set_log_file')
  let fileLogWriterObj.set_colorize = function('<SNR>' . s:SID() . '_s:FileLogWriter_set_colorize')
  let fileLogWriterObj.get_colorize = function('<SNR>' . s:SID() . '_s:FileLogWriter_get_colorize')
  let fileLogWriterObj.log = function('<SNR>' . s:SID() . '_s:FileLogWriter_log')
  let fileLogWriterObj.flush = function('<SNR>' . s:SID() . '_s:FileLogWriter_flush')
  return fileLogWriterObj
endfunction
function! <SID>s:FileLogWriter_set_log_file(log_file) dict
  call self.writer.set_output_file(a:log_file)
endfunction
function! <SID>s:FileLogWriter_set_colorize(colorize) dict
  let self.colorize = a:colorize
endfunction
function! <SID>s:FileLogWriter_get_colorize() dict
  return self.colorize
endfunction
function! <SID>s:FileLogWriter_log(message) dict
  call self.writer.writeln(a:message)
endfunction
function! <SID>s:FileLogWriter_flush() dict
  call self.writer.flush()
endfunction
" included: 'base_reporter.riml'
function! s:BaseReporterConstructor()
  let baseReporterObj = {}
  let baseReporterObj.colorize_output = 1
  let baseReporterObj.log_buffer = []
  let baseReporterObj.set_writer = function('<SNR>' . s:SID() . '_s:BaseReporter_set_writer')
  let baseReporterObj.on_start = function('<SNR>' . s:SID() . '_s:BaseReporter_on_start')
  let baseReporterObj.on_end = function('<SNR>' . s:SID() . '_s:BaseReporter_on_end')
  let baseReporterObj.on_context_start = function('<SNR>' . s:SID() . '_s:BaseReporter_on_context_start')
  let baseReporterObj.on_context_end = function('<SNR>' . s:SID() . '_s:BaseReporter_on_context_end')
  let baseReporterObj.on_spec_start = function('<SNR>' . s:SID() . '_s:BaseReporter_on_spec_start')
  let baseReporterObj.on_spec_end = function('<SNR>' . s:SID() . '_s:BaseReporter_on_spec_end')
  let baseReporterObj.on_spec_pass = function('<SNR>' . s:SID() . '_s:BaseReporter_on_spec_pass')
  let baseReporterObj.on_spec_failure = function('<SNR>' . s:SID() . '_s:BaseReporter_on_spec_failure')
  let baseReporterObj.on_spec_error = function('<SNR>' . s:SID() . '_s:BaseReporter_on_spec_error')
  let baseReporterObj.on_spec_pending = function('<SNR>' . s:SID() . '_s:BaseReporter_on_spec_pending')
  let baseReporterObj.duration_to_str = function('<SNR>' . s:SID() . '_s:BaseReporter_duration_to_str')
  let baseReporterObj.get_duration_msg = function('<SNR>' . s:SID() . '_s:BaseReporter_get_duration_msg')
  let baseReporterObj.write_epilogue_separator = function('<SNR>' . s:SID() . '_s:BaseReporter_write_epilogue_separator')
  let baseReporterObj.write_epilogue = function('<SNR>' . s:SID() . '_s:BaseReporter_write_epilogue')
  let baseReporterObj.set_colorize_output = function('<SNR>' . s:SID() . '_s:BaseReporter_set_colorize_output')
  let baseReporterObj.get_colorize_output = function('<SNR>' . s:SID() . '_s:BaseReporter_get_colorize_output')
  let baseReporterObj.colorize = function('<SNR>' . s:SID() . '_s:BaseReporter_colorize')
  let baseReporterObj.to_color = function('<SNR>' . s:SID() . '_s:BaseReporter_to_color')
  let baseReporterObj.to_red = function('<SNR>' . s:SID() . '_s:BaseReporter_to_red')
  let baseReporterObj.to_green = function('<SNR>' . s:SID() . '_s:BaseReporter_to_green')
  let baseReporterObj.get_tick_icon = function('<SNR>' . s:SID() . '_s:BaseReporter_get_tick_icon')
  let baseReporterObj.get_cross_icon = function('<SNR>' . s:SID() . '_s:BaseReporter_get_cross_icon')
  let baseReporterObj.get_tick = function('<SNR>' . s:SID() . '_s:BaseReporter_get_tick')
  let baseReporterObj.get_cross = function('<SNR>' . s:SID() . '_s:BaseReporter_get_cross')
  let baseReporterObj.get_colorize = function('<SNR>' . s:SID() . '_s:BaseReporter_get_colorize')
  let baseReporterObj.log = function('<SNR>' . s:SID() . '_s:BaseReporter_log')
  let baseReporterObj.has_logs = function('<SNR>' . s:SID() . '_s:BaseReporter_has_logs')
  let baseReporterObj.flush_log_buffer = function('<SNR>' . s:SID() . '_s:BaseReporter_flush_log_buffer')
  let baseReporterObj.write_log_line = function('<SNR>' . s:SID() . '_s:BaseReporter_write_log_line')
  return baseReporterObj
endfunction
function! <SID>s:BaseReporter_set_writer(writer) dict
  let self.writer = a:writer
endfunction
function! <SID>s:BaseReporter_on_start(stats) dict
endfunction
function! <SID>s:BaseReporter_on_end(duration, stats) dict
  call self.write_epilogue(a:duration, a:stats)
endfunction
function! <SID>s:BaseReporter_on_context_start(context, stats) dict
endfunction
function! <SID>s:BaseReporter_on_context_end(context, stats) dict
endfunction
function! <SID>s:BaseReporter_on_spec_start(meta, stats) dict
endfunction
function! <SID>s:BaseReporter_on_spec_end(meta, stats) dict
endfunction
function! <SID>s:BaseReporter_on_spec_pass(meta, stats) dict
endfunction
function! <SID>s:BaseReporter_on_spec_failure(meta, err, stats) dict
endfunction
function! <SID>s:BaseReporter_on_spec_error(meta, err, stats) dict
endfunction
function! <SID>s:BaseReporter_on_spec_pending(meta, stats) dict
endfunction
function! <SID>s:BaseReporter_duration_to_str(duration) dict
  let time = a:duration
  if time >=# 1000
    let time = time / 1000
    return time . "s"
  else
    return time . "ms"
  endif
endfunction
function! <SID>s:BaseReporter_get_duration_msg(meta) dict
  if a:meta.is_slow()
    let duration_str = self.duration_to_str(a:meta.get_duration())
    return "(" . duration_str . ")"
  else
    return ''
  endif
endfunction
function! <SID>s:BaseReporter_write_epilogue_separator() dict
  call self.writer.writeln("----------------------------------------------------")
endfunction
function! <SID>s:BaseReporter_write_epilogue(duration, stats) dict
  call self.write_epilogue_separator()
  let duration_str = self.duration_to_str(a:duration)
  if a:stats.is_ok()
    let icon = self.get_tick_icon()
  else
    let icon = self.get_cross_icon()
  endif
  call self.writer.writeln(self.to_color(icon . " " . a:stats.get_count() . " tests completed (" . duration_str . ")", a:stats))
  call self.writer.writeln("Passed: " . a:stats.get_passes() . ", Failures: " . a:stats.get_failures() . ", Errors: " . a:stats.get_errors() . ", Assertions: " . a:stats.get_assertions())
endfunction
function! <SID>s:BaseReporter_set_colorize_output(colorize_output) dict
  let self.colorize_output = a:colorize_output
endfunction
function! <SID>s:BaseReporter_get_colorize_output() dict
  return self.colorize_output
endfunction
function! <SID>s:BaseReporter_colorize(str, color) dict
  if self.get_colorize_output()
    return "[" . a:color . a:str . "[0m"
  else
    return a:str
  endif
endfunction
function! <SID>s:BaseReporter_to_color(str, stats) dict
  if a:stats.is_ok()
    return self.to_green(a:str)
  else
    return self.to_red(a:str)
  endif
endfunction
function! <SID>s:BaseReporter_to_red(str) dict
  return self.colorize(a:str, '31m')
endfunction
function! <SID>s:BaseReporter_to_green(str) dict
  return self.colorize(a:str, '32m')
endfunction
function! <SID>s:BaseReporter_get_tick_icon() dict
  return '✓'
endfunction
function! <SID>s:BaseReporter_get_cross_icon() dict
  return '✖'
endfunction
function! <SID>s:BaseReporter_get_tick() dict
  return self.to_green(self.get_tick_icon())
endfunction
function! <SID>s:BaseReporter_get_cross() dict
  return self.to_red(self.get_cross_icon())
endfunction
function! <SID>s:BaseReporter_get_colorize() dict
  return self.get_colorize_output()
endfunction
function! <SID>s:BaseReporter_log(message) dict
  call add(self.log_buffer, a:message)
endfunction
function! <SID>s:BaseReporter_has_logs() dict
  return len(self.log_buffer) ># 0
endfunction
function! <SID>s:BaseReporter_flush_log_buffer() dict
  if self.has_logs()
    call self.writer.writeln('')
    for line in self.log_buffer
      call self.write_log_line(line)
    endfor
    call self.writer.writeln('')
    let self.log_buffer = []
  endif
endfunction
function! <SID>s:BaseReporter_write_log_line(line) dict
  call self.writer.writeln("log: " . a:line)
endfunction
" included: 'spec_reporter.riml'
function! s:SpecReporterConstructor()
  let specReporterObj = {}
  let baseReporterObj = s:BaseReporterConstructor()
  call extend(specReporterObj, baseReporterObj)
  let specReporterObj.indents = 0
  let specReporterObj.log_buffer = []
  let specReporterObj.write = function('<SNR>' . s:SID() . '_s:SpecReporter_write')
  let specReporterObj.on_start = function('<SNR>' . s:SID() . '_s:SpecReporter_on_start')
  let specReporterObj.on_context_start = function('<SNR>' . s:SID() . '_s:SpecReporter_on_context_start')
  let specReporterObj.on_context_end = function('<SNR>' . s:SID() . '_s:SpecReporter_on_context_end')
  let specReporterObj.on_spec_pass = function('<SNR>' . s:SID() . '_s:SpecReporter_on_spec_pass')
  let specReporterObj.on_spec_failure = function('<SNR>' . s:SID() . '_s:SpecReporter_on_spec_failure')
  let specReporterObj.on_spec_error = function('<SNR>' . s:SID() . '_s:SpecReporter_on_spec_error')
  let specReporterObj.indent_to_str = function('<SNR>' . s:SID() . '_s:SpecReporter_indent_to_str')
  let specReporterObj.indent = function('<SNR>' . s:SID() . '_s:SpecReporter_indent')
  let specReporterObj.unindent = function('<SNR>' . s:SID() . '_s:SpecReporter_unindent')
  let specReporterObj.write_epilogue_separator = function('<SNR>' . s:SID() . '_s:SpecReporter_write_epilogue_separator')
  let specReporterObj.write_log_line = function('<SNR>' . s:SID() . '_s:SpecReporter_write_log_line')
  let specReporterObj.BaseReporter_write_epilogue_separator = function('<SNR>' . s:SID() . '_s:BaseReporter_write_epilogue_separator')
  return specReporterObj
endfunction
function! <SID>s:SpecReporter_write(msg) dict
  let line = self.indent_to_str() . a:msg
  call self.writer.writeln(line)
endfunction
function! <SID>s:SpecReporter_on_start(stats) dict
endfunction
function! <SID>s:SpecReporter_on_context_start(context, stats) dict
  call self.write(a:context)
  call self.indent(1)
endfunction
function! <SID>s:SpecReporter_on_context_end(context, stats) dict
  call self.unindent(1)
endfunction
function! <SID>s:SpecReporter_on_spec_pass(meta, stats) dict
  let duration_msg = self.get_duration_msg(a:meta)
  call self.write(self.get_tick() . " " . a:meta.get_sentence() . " " . duration_msg)
  call self.indent(2)
  call self.flush_log_buffer()
  call self.unindent(2)
endfunction
function! <SID>s:SpecReporter_on_spec_failure(meta, err, stats) dict
  call self.write(self.get_cross() . " " . self.to_red(a:meta.get_sentence()))
  call self.indent(2)
  call self.write(self.to_red(a:err))
  call self.flush_log_buffer()
  call self.unindent(2)
endfunction
function! <SID>s:SpecReporter_on_spec_error(meta, err, stats) dict
  call self.on_spec_failure(a:meta, a:err, a:stats)
endfunction
function! <SID>s:SpecReporter_indent_to_str() dict
  return repeat("  ", self.indents)
endfunction
function! <SID>s:SpecReporter_indent(size) dict
  let self.indents += a:size
endfunction
function! <SID>s:SpecReporter_unindent(size) dict
  let self.indents -= a:size
endfunction
function! <SID>s:SpecReporter_write_epilogue_separator() dict
  call self.writer.writeln('')
  call self.BaseReporter_write_epilogue_separator()
endfunction
function! <SID>s:SpecReporter_write_log_line(line) dict
  call self.write("log: " . a:line)
endfunction
" included: 'min_reporter.riml'
function! s:MinReporterConstructor()
  let minReporterObj = {}
  let baseReporterObj = s:BaseReporterConstructor()
  call extend(minReporterObj, baseReporterObj)
  let minReporterObj.on_spec_failure = function('<SNR>' . s:SID() . '_s:MinReporter_on_spec_failure')
  let minReporterObj.on_spec_error = function('<SNR>' . s:SID() . '_s:MinReporter_on_spec_error')
  let minReporterObj.write_epilogue_separator = function('<SNR>' . s:SID() . '_s:MinReporter_write_epilogue_separator')
  let minReporterObj.BaseReporter_write_epilogue_separator = function('<SNR>' . s:SID() . '_s:BaseReporter_write_epilogue_separator')
  return minReporterObj
endfunction
function! <SID>s:MinReporter_on_spec_failure(meta, err, stats) dict
  let name = a:meta.get_sentence()
  let context = a:meta.get_context()
  call self.writer.writeln(self.to_red(context . " #" . name . " - " . a:err))
endfunction
function! <SID>s:MinReporter_on_spec_error(meta, err, stats) dict
  call self.on_spec_failure(a:meta, a:err, a:stats)
endfunction
function! <SID>s:MinReporter_write_epilogue_separator() dict
  call self.flush_log_buffer()
  call self.BaseReporter_write_epilogue_separator()
endfunction
" included: 'tap_reporter.riml'
function! s:TAPReporterConstructor()
  let tAPReporterObj = {}
  let baseReporterObj = s:BaseReporterConstructor()
  call extend(tAPReporterObj, baseReporterObj)
  let tAPReporterObj.on_start = function('<SNR>' . s:SID() . '_s:TAPReporter_on_start')
  let tAPReporterObj.on_spec_start = function('<SNR>' . s:SID() . '_s:TAPReporter_on_spec_start')
  let tAPReporterObj.on_spec_end = function('<SNR>' . s:SID() . '_s:TAPReporter_on_spec_end')
  let tAPReporterObj.on_spec_pass = function('<SNR>' . s:SID() . '_s:TAPReporter_on_spec_pass')
  let tAPReporterObj.on_spec_failure = function('<SNR>' . s:SID() . '_s:TAPReporter_on_spec_failure')
  let tAPReporterObj.on_spec_error = function('<SNR>' . s:SID() . '_s:TAPReporter_on_spec_error')
  let tAPReporterObj.on_spec_pending = function('<SNR>' . s:SID() . '_s:TAPReporter_on_spec_pending')
  let tAPReporterObj.get_preamble = function('<SNR>' . s:SID() . '_s:TAPReporter_get_preamble')
  return tAPReporterObj
endfunction
function! <SID>s:TAPReporter_on_start(stats) dict
endfunction
function! <SID>s:TAPReporter_on_spec_start(meta, stats) dict
endfunction
function! <SID>s:TAPReporter_on_spec_end(meta, stats) dict
endfunction
function! <SID>s:TAPReporter_on_spec_pass(meta, stats) dict
  let name = a:meta.get_sentence()
  let duration_msg = self.get_duration_msg(a:meta)
  let preamble = self.get_preamble('ok', a:stats.get_count(), a:meta.get_context())
  call self.writer.writeln(preamble . " #" . name . " " . duration_msg)
  call self.flush_log_buffer()
endfunction
function! <SID>s:TAPReporter_on_spec_failure(meta, err, stats) dict
  let name = a:meta.get_sentence()
  let preamble = self.get_preamble('not ok', a:stats.get_count(), a:meta.get_context())
  call self.writer.writeln(preamble . " #" . name . " - " . a:err)
  call self.flush_log_buffer()
endfunction
function! <SID>s:TAPReporter_on_spec_error(meta, err, stats) dict
  let name = a:meta.get_sentence()
  let preamble = self.get_preamble('not ok', a:stats.get_count(), a:meta.get_context())
  call self.writer.writeln(preamble . " #" . name . " - " . a:err)
  call self.flush_log_buffer()
endfunction
function! <SID>s:TAPReporter_on_spec_pending(meta, stats) dict
endfunction
function! <SID>s:TAPReporter_get_preamble(status, count, context) dict
  let msg = a:status . " " . a:count . " - " . a:context
  return msg
endfunction
" included: 'dotmatrix_reporter.riml'
function! s:DotMatrixReporterConstructor()
  let dotMatrixReporterObj = {}
  let baseReporterObj = s:BaseReporterConstructor()
  call extend(dotMatrixReporterObj, baseReporterObj)
  let dotMatrixReporterObj.dots = 0
  let dotMatrixReporterObj.line_buffer = []
  let dotMatrixReporterObj.log_messages = []
  let dotMatrixReporterObj.write = function('<SNR>' . s:SID() . '_s:DotMatrixReporter_write')
  let dotMatrixReporterObj.on_spec_pass = function('<SNR>' . s:SID() . '_s:DotMatrixReporter_on_spec_pass')
  let dotMatrixReporterObj.on_spec_failure = function('<SNR>' . s:SID() . '_s:DotMatrixReporter_on_spec_failure')
  let dotMatrixReporterObj.on_spec_error = function('<SNR>' . s:SID() . '_s:DotMatrixReporter_on_spec_error')
  let dotMatrixReporterObj.write_epilogue_separator = function('<SNR>' . s:SID() . '_s:DotMatrixReporter_write_epilogue_separator')
  return dotMatrixReporterObj
endfunction
function! <SID>s:DotMatrixReporter_write(msg) dict
  if self.dots ># 50
    call self.writer.writeln(a:msg)
    let self.dots = 0
  else
    call self.writer.write(a:msg)
  endif
endfunction
function! <SID>s:DotMatrixReporter_on_spec_pass(meta, stats) dict
  let self.dots += 1
  call self.write('.')
endfunction
function! <SID>s:DotMatrixReporter_on_spec_failure(meta, err, stats) dict
  let self.dots += 1
  call self.write(self.to_red("x"))
  let name = a:meta.get_sentence()
  let context = a:meta.get_context()
  call add(self.line_buffer, self.to_red(context . " #" . name))
  call add(self.line_buffer, self.to_red("    " . a:err))
  call add(self.line_buffer, '')
endfunction
function! <SID>s:DotMatrixReporter_on_spec_error(meta, err, stats) dict
  call self.on_spec_failure(a:meta, a:err, a:stats)
endfunction
function! <SID>s:DotMatrixReporter_write_epilogue_separator() dict
  call self.flush_log_buffer()
  call self.writer.writeln('')
  for line in self.line_buffer
    call self.writer.writeln(line)
  endfor
  call self.writer.writeln("")
endfunction
" included: 'reporter_factory.riml'
function! s:ReporterFactoryConstructor()
  let reporterFactoryObj = {}
  let reporterFactoryObj.get_reporter = function('<SNR>' . s:SID() . '_s:ReporterFactory_get_reporter')
  return reporterFactoryObj
endfunction
function! <SID>s:ReporterFactory_get_reporter(reporter_name) dict
  if a:reporter_name ==# 'spec'
    return s:SpecReporterConstructor()
  elseif a:reporter_name ==# 'min'
    return s:MinReporterConstructor()
  elseif a:reporter_name ==# 'tap'
    return s:TAPReporterConstructor()
  elseif a:reporter_name ==# 'dot'
    return s:DotMatrixReporterConstructor()
  else
    return s:SpecReporterConstructor()
  endif
endfunction
" included: 'spec_runner.riml'
function! s:SpecRunnerConstructor(spec)
  let specRunnerObj = {}
  let specRunnerObj.spec = a:spec
  let specRunnerObj.stopped = 0
  let specRunnerObj.bail = 0
  let specRunnerObj.bailed = 0
  let specRunnerObj.tag = ''
  let specRunnerObj.set_bail = function('<SNR>' . s:SID() . '_s:SpecRunner_set_bail')
  let specRunnerObj.set_tag = function('<SNR>' . s:SID() . '_s:SpecRunner_set_tag')
  let specRunnerObj.has_bailed = function('<SNR>' . s:SID() . '_s:SpecRunner_has_bailed')
  let specRunnerObj.start = function('<SNR>' . s:SID() . '_s:SpecRunner_start')
  let specRunnerObj.call_hook = function('<SNR>' . s:SID() . '_s:SpecRunner_call_hook')
  let specRunnerObj.stop = function('<SNR>' . s:SID() . '_s:SpecRunner_stop')
  let specRunnerObj.is_test_method = function('<SNR>' . s:SID() . '_s:SpecRunner_is_test_method')
  let specRunnerObj.is_method_tagged = function('<SNR>' . s:SID() . '_s:SpecRunner_is_method_tagged')
  let specRunnerObj.can_run_test_for = function('<SNR>' . s:SID() . '_s:SpecRunner_can_run_test_for')
  return specRunnerObj
endfunction
function! <SID>s:SpecRunner_set_bail(bail) dict
  let self.bail = a:bail
endfunction
function! <SID>s:SpecRunner_set_tag(tag) dict
  let self.tag = a:tag
endfunction
function! <SID>s:SpecRunner_has_bailed() dict
  return self.bailed
endfunction
function! <SID>s:SpecRunner_start(reporter, stats) dict
  let spec = self.spec
  let did_fail = 0
  let context = self.call_hook('describe')
  call a:reporter.on_context_start(context, a:stats)
  call self.call_hook('before')
  for method in keys(spec)
    if self.stopped
      break
    endif
    if self.can_run_test_for(method)
      let timer = s:SpecTimerConstructor()
      let meta = s:SpecMetaConstructor(context, method)
      call a:reporter.on_spec_start(meta, a:stats)
      let result = 0
      try
        call self.call_hook('before_each')
        call timer.start()
        call eval("spec." . method . "()")
        call timer.stop()
        call self.call_hook('after_each')
        call meta.set_duration(timer.get_duration())
        call a:stats.inc_passes()
        call a:reporter.on_spec_pass(meta, a:stats)
      catch /Unknown function.*expect/
        let did_fail = 1
        call a:stats.inc_failures()
        let exception = 'DSLError: expect() not found, dsl.riml may not be included'
        call a:reporter.on_spec_failure(meta, exception, a:stats)
      catch /Unknown function.*define_matcher/
        let did_fail = 1
        call a:stats.inc_failures()
        let exception = 'DSLError: define_matcher() not found, dsl.riml may not be included'
        call a:reporter.on_spec_failure(meta, exception, a:stats)
      catch /^AssertionError/
        let did_fail = 1
        call a:stats.inc_failures()
        call a:reporter.on_spec_failure(meta, v:exception, a:stats)
      catch /.*/
        let did_fail = 1
        call a:stats.inc_errors()
        call a:reporter.on_spec_error(meta, v:exception, a:stats)
      endtry
      call a:reporter.on_spec_end(meta, a:stats)
      redraw
      if did_fail && self.bail
        let self.bailed = 1
        break
      endif
    endif
  endfor
  call self.call_hook('after')
  call a:reporter.on_context_end(context, a:stats)
endfunction
function! <SID>s:SpecRunner_call_hook(hook) dict
  let spec = self.spec
  if has_key(spec, a:hook)
    return eval("spec." . a:hook . "()")
  else
    return "Undefined hook: " . a:hook
  endif
endfunction
function! <SID>s:SpecRunner_stop() dict
  let self.stopped = 1
endfunction
function! <SID>s:SpecRunner_is_test_method(method) dict
  return a:method =~# '^it'
endfunction
function! <SID>s:SpecRunner_is_method_tagged(method) dict
  return a:method =~# "_" . self.tag . "$"
endfunction
function! <SID>s:SpecRunner_can_run_test_for(method) dict
  if self.tag ==# ''
    return self.is_test_method(a:method)
  else
    return self.is_test_method(a:method) && self.is_method_tagged(a:method)
  endif
endfunction
" included: 'runner.riml'
function! s:RunnerConstructor()
  let runnerObj = {}
  let runnerObj.specs = []
  let runnerObj.halt = 0
  let runnerObj.stopped = 0
  let runnerObj.bail = 0
  let runnerObj.tag = ''
  let runnerObj.set_bail = function('<SNR>' . s:SID() . '_s:Runner_set_bail')
  let runnerObj.get_bail = function('<SNR>' . s:SID() . '_s:Runner_get_bail')
  let runnerObj.set_tag = function('<SNR>' . s:SID() . '_s:Runner_set_tag')
  let runnerObj.get_tag = function('<SNR>' . s:SID() . '_s:Runner_get_tag')
  let runnerObj.add = function('<SNR>' . s:SID() . '_s:Runner_add')
  let runnerObj.start = function('<SNR>' . s:SID() . '_s:Runner_start')
  let runnerObj.stop = function('<SNR>' . s:SID() . '_s:Runner_stop')
  return runnerObj
endfunction
function! <SID>s:Runner_set_bail(bail) dict
  let self.bail = a:bail
endfunction
function! <SID>s:Runner_get_bail() dict
  return self.bail
endfunction
function! <SID>s:Runner_set_tag(tag) dict
  let self.tag = a:tag
endfunction
function! <SID>s:Runner_get_tag() dict
  return self.tag
endfunction
function! <SID>s:Runner_add(spec) dict
  call add(self.specs, a:spec)
endfunction
function! <SID>s:Runner_start(reporter, stats) dict
  call a:reporter.on_start(a:stats)
  let timer = s:SpecTimerConstructor()
  call timer.start()
  for spec in self.specs
    if self.stopped
      break
    endif
    let spec_runner = s:SpecRunnerConstructor(spec)
    call spec_runner.set_bail(self.get_bail())
    call spec_runner.set_tag(self.get_tag())
    call spec_runner.start(a:reporter, a:stats)
    if spec_runner.has_bailed()
      let self.stopped = 1
    endif
  endfor
  call timer.stop()
  call a:reporter.on_end(timer.get_duration(), a:stats)
endfunction
function! <SID>s:Runner_stop() dict
  let self.stopped = 1
endfunction
" included: 'expectation.riml'
function! g:ExpectationConstructor(actual)
  let expectationObj = {}
  let expectationObj.actual = a:actual
  let expectationObj.load = function('<SNR>' . s:SID() . '_s:Expectation_load')
  return expectationObj
endfunction
function! <SID>s:Expectation_load(matchers) dict
  call a:matchers.load_defaults()
  let match_tester = g:MatchTesterConstructor()
  let match_items = a:matchers.get_match_items()
  for match_item in match_items
    let func_name = "g:Expectation_" . match_item.name
    let matcher_func = "function! " . func_name . "(...) dict  \n  if a:0 == 0\n    let expected = 'null'\n  else\n    let expected = a:1\n  endif\n\n  let matcher_name = '" . match_item.name . "'\n  let match_tester = g:MatchTesterConstructor()\n  call match_tester.test_from_env(matcher_name, expected)\"\nendfunction\"   "
    exe matcher_func
    let self[match_item.name] = function(func_name)
  endfor
endfunction
function! g:SpeckleConstructor()
  let speckleObj = {}
  let speckleObj.configure = function('<SNR>' . s:SID() . '_s:Speckle_configure')
  let speckleObj.options = function('<SNR>' . s:SID() . '_s:Speckle_options')
  let speckleObj.option = function('<SNR>' . s:SID() . '_s:Speckle_option')
  let speckleObj.get_writer = function('<SNR>' . s:SID() . '_s:Speckle_get_writer')
  let speckleObj.get_reporter = function('<SNR>' . s:SID() . '_s:Speckle_get_reporter')
  let speckleObj.is_file_mode = function('<SNR>' . s:SID() . '_s:Speckle_is_file_mode')
  let speckleObj.get_output_file = function('<SNR>' . s:SID() . '_s:Speckle_get_output_file')
  let speckleObj.get_reporter_name = function('<SNR>' . s:SID() . '_s:Speckle_get_reporter_name')
  let speckleObj.get_slow_threshold = function('<SNR>' . s:SID() . '_s:Speckle_get_slow_threshold')
  let speckleObj.get_colorize = function('<SNR>' . s:SID() . '_s:Speckle_get_colorize')
  let speckleObj.get_bail = function('<SNR>' . s:SID() . '_s:Speckle_get_bail')
  let speckleObj.get_tag = function('<SNR>' . s:SID() . '_s:Speckle_get_tag')
  let speckleObj.run = function('<SNR>' . s:SID() . '_s:Speckle_run')
  let speckleObj.add_specs = function('<SNR>' . s:SID() . '_s:Speckle_add_specs')
  return speckleObj
endfunction
function! <SID>s:Speckle_configure() dict
  let options_map = {'output_file': '"speckle.log"', 'file_mode': '0', 'reporter_name': '"spec"', 'slow_threshold': '10', 'colorize': '1', 'bail': '0', 'tag': '""'}
  call self.options(options_map)
endfunction
function! <SID>s:Speckle_options(options_map) dict
  for [name, value] in items(a:options_map)
    call self.option(name, value)
  endfor
endfunction
function! <SID>s:Speckle_option(variable, default) dict
  if !exists("g:speckle_" . a:variable)
    execute "let g:speckle_" . a:variable . " = " . a:default
  endif
endfunction
function! <SID>s:Speckle_get_writer() dict
  let factory = s:WriterFactoryConstructor()
  let writer = factory.get_writer('buffer')
  if self.is_file_mode()
    call writer.set_output_file(self.get_output_file())
  endif
  return writer
endfunction
function! <SID>s:Speckle_get_reporter(writer) dict
  let factory = s:ReporterFactoryConstructor()
  let reporter = factory.get_reporter(self.get_reporter_name())
  call reporter.set_writer(a:writer)
  let logger = s:get_logger()
  call logger.add_log_writer(reporter)
  return reporter
endfunction
function! <SID>s:Speckle_is_file_mode() dict
  return g:speckle_file_mode
endfunction
function! <SID>s:Speckle_get_output_file() dict
  return g:speckle_output_file
endfunction
function! <SID>s:Speckle_get_reporter_name() dict
  return g:speckle_reporter_name
endfunction
function! <SID>s:Speckle_get_slow_threshold() dict
  return g:speckle_slow_threshold
endfunction
function! <SID>s:Speckle_get_colorize() dict
  return g:speckle_colorize
endfunction
function! <SID>s:Speckle_get_bail() dict
  return g:speckle_bail
endfunction
function! <SID>s:Speckle_get_tag() dict
  return g:speckle_tag
endfunction
function! <SID>s:Speckle_run() dict
  call self.configure()
  let writer = self.get_writer()
  let stats = s:StatisticianConstructor()
  let reporter = self.get_reporter(writer)
  call reporter.set_colorize_output(self.get_colorize())
  let runner = s:RunnerConstructor()
  call runner.set_bail(self.get_bail())
  call runner.set_tag(self.get_tag())
  let functions = ''
  redir => functions
  silent function /SpecConstructor$/
  redir END
  call self.add_specs(runner, functions)
  call runner.start(reporter, stats)
  if self.is_file_mode()
    call writer.flush()
  endif
endfunction
function! <SID>s:Speckle_add_specs(runner, lines) dict
  let classes = split(a:lines, "\n")
  call map(classes, "substitute(v:val, 'function ', '', '')")
  for klass in classes
    call eval("a:runner.add(" . klass . ")")
  endfor
endfunction
